/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrandForm: typeof import('./src/modules/brands/components/BrandForm.vue')['default']
    CostsTableForm: typeof import('./src/modules/costsTable/components/CostsTableForm.vue')['default']
    CostTableDetailsModel: typeof import('./src/modules/costsTable/components/CostTableDetailsModel/CostTableDetailsModel.vue')['default']
    CostTableDetailsSkeleton: typeof import('./src/modules/costsTable/components/CostTableDetailsModel/CostTableDetailsSkeleton.vue')['default']
    CostTableInfoModel: typeof import('./src/modules/costsTable/components/CostTableInfoModel/CostTableInfoModel.vue')['default']
    EEditableListItem: typeof import('./src/core/components/EInput/EEditableListItem.vue')['default']
    EError: typeof import('./src/core/components/EError.vue')['default']
    EForm: typeof import('./src/core/components/EForm.vue')['default']
    EGenericIdView: typeof import('./src/core/components/EGeneric/EGenericIdView.vue')['default']
    EInputPct: typeof import('./src/core/components/EInput/EInputPct.vue')['default']
    EInputPrice: typeof import('./src/core/components/EInput/EInputPrice.vue')['default']
    ELayout: typeof import('./src/core/components/ELayout.vue')['default']
    EOrderBy: typeof import('./src/core/components/EOrderBy.vue')['default']
    ESelectBrands: typeof import('./src/core/components/ESelect/ESelectBrands.vue')['default']
    ESelectCostsTable: typeof import('./src/core/components/ESelect/ESelectCostsTable.vue')['default']
    ESelectFamilies: typeof import('./src/core/components/ESelect/ESelectFamilies.vue')['default']
    ESelectFeedstocks: typeof import('./src/core/components/ESelect/ESelectFeedstocks.vue')['default']
    ESelectPeople: typeof import('./src/core/components/ESelect/ESelectPeople.vue')['default']
    ESelectPricesTable: typeof import('./src/core/components/ESelect/ESelectPricesTable.vue')['default']
    ESelectProducts: typeof import('./src/core/components/ESelect/ESelectProducts.vue')['default']
    ESelectQuery: typeof import('./src/core/components/ESelect/ESelectQuery.vue')['default']
    ESelectStates: typeof import('./src/core/components/ESelect/ESelectStates.vue')['default']
    ETable: typeof import('./src/core/components/ETable/ETable.vue')['default']
    ETableActionButtons: typeof import('./src/core/components/ETable/ETableActionButtons.vue')['default']
    ETableCellUpdate: typeof import('./src/core/components/ETable/ETableCellUpdate.vue')['default']
    ETableGenericList: typeof import('./src/core/components/ETable/ETableGenericList.vue')['default']
    ETableOrderBy: typeof import('./src/core/components/ETable/ETableOrderBy.vue')['default']
    FamiliesForm: typeof import('./src/modules/families/components/FamiliesForm.vue')['default']
    FeedStockForm: typeof import('./src/modules/feedstocks/components/feedStockForm.vue')['default']
    LoginForm: typeof import('./src/modules/users/components/LoginForm.vue')['default']
    PersonForm: typeof import('./src/modules/people/components/PersonForm.vue')['default']
    PricesTabelaSummary: typeof import('./src/modules/pricesTable/components/PricesTabelaSummary.vue')['default']
    PricesTableCostsDetail: typeof import('./src/modules/pricesTable/components/PricesTableCostsDetail.vue')['default']
    PricesTableForm: typeof import('./src/modules/pricesTable/components/PricesTableForm.vue')['default']
    PricesTableSummary: typeof import('./src/modules/pricesTable/components/PricesTableSummary.vue')['default']
    ProductDetailsInfo: typeof import('./src/modules/products/components/ProductDetailsModel/tabs/ProductDetailsInfo.vue')['default']
    ProductDetailsModel: typeof import('./src/modules/products/components/ProductDetailsModel/ProductDetailsModel.vue')['default']
    ProductDetailsProduction: typeof import('./src/modules/products/components/ProductDetailsModel/tabs/ProductDetailsProduction.vue')['default']
    ProductDetailsSkeleton: typeof import('./src/modules/products/components/ProductDetailsModel/ProductDetailsSkeleton.vue')['default']
    ProductForm: typeof import('./src/modules/products/components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsForm: typeof import('./src/modules/settings/components/SettingsForm.vue')['default']
    UserForm: typeof import('./src/modules/users/components/UserForm.vue')['default']
  }
}
