/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrandForm: typeof import('./src/modules/records/brands/components/BrandForm.vue')['default']
    EError: typeof import('./src/core/components/EError.vue')['default']
    EForm: typeof import('./src/core/components/EForm.vue')['default']
    EGenericIdView: typeof import('./src/core/components/EGeneric/EGenericIdView.vue')['default']
    ELayout: typeof import('./src/core/components/ELayout.vue')['default']
    ESelectBrands: typeof import('./src/core/components/ESelect/ESelectBrands.vue')['default']
    ESelectQuery: typeof import('./src/core/components/ESelect/ESelectQuery.vue')['default']
    ESelectStates: typeof import('./src/core/components/ESelect/ESelectStates.vue')['default']
    ETable: typeof import('./src/core/components/ETable/ETable.vue')['default']
    ETableActionButtons: typeof import('./src/core/components/ETable/ETableActionButtons.vue')['default']
    ETableGenericList: typeof import('./src/core/components/ETable/ETableGenericList.vue')['default']
    ETableListRegister: typeof import('./src/core/components/ETable/ETableListRegister.vue')['default']
    FeedStockForm: typeof import('./src/modules/records/feedstocks/components/feedStockForm.vue')['default']
    LoginForm: typeof import('./src/modules/auth/users/components/LoginForm.vue')['default']
    PersonForm: typeof import('./src/modules/records/people/components/PersonForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/modules/auth/users/components/UserForm.vue')['default']
  }
}
