/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EError: typeof import('./src/core/components/EError.vue')['default']
    ELayout: typeof import('./src/core/components/ELayout.vue')['default']
    ETable: typeof import('./src/core/components/ETable.vue')['default']
    ETableActionButtons: typeof import('./src/core/components/ETableActionButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
